import { Module, Resource, Action } from '@prisma/client';

/**
 * System Permissions Constants
 */

export interface PermissionDefinition {
  name: string;
  code: string;
  description: string;
  module: Module;
  resource: Resource;
  action: Action;
  displayOrder: number;
}

export const IDENTITY_PERMISSIONS: PermissionDefinition[] = [
  // USER Permissions
  {
    name: 'Create User',
    code: 'USER_CREATE',
    description: 'Allows creating new user accounts.',
    module: Module.IDENTITY,
    resource: Resource.USER,
    action: Action.CREATE,
    displayOrder: 1,
  },
  {
    name: 'Read User',
    code: 'USER_READ',
    description: 'Allows viewing user profiles and lists.',
    module: Module.IDENTITY,
    resource: Resource.USER,
    action: Action.READ,
    displayOrder: 2,
  },
  {
    name: 'Update User',
    code: 'USER_UPDATE',
    description: 'Allows editing existing user accounts.',
    module: Module.IDENTITY,
    resource: Resource.USER,
    action: Action.UPDATE,
    displayOrder: 3,
  },
  {
    name: 'Delete User',
    code: 'USER_DELETE',
    description: 'Allows deleting or deactivating user accounts.',
    module: Module.IDENTITY,
    resource: Resource.USER,
    action: Action.DELETE,
    displayOrder: 4,
  },

  // ROLE Permissions
  {
    name: 'Create Role',
    code: 'ROLE_CREATE',
    description: 'Allows creating new system or custom roles.',
    module: Module.IDENTITY,
    resource: Resource.ROLE,
    action: Action.CREATE,
    displayOrder: 5,
  },
  {
    name: 'Read Role',
    code: 'ROLE_READ',
    description: 'Allows viewing roles and hierarchy settings.',
    module: Module.IDENTITY,
    resource: Resource.ROLE,
    action: Action.READ,
    displayOrder: 6,
  },
  {
    name: 'Update Role',
    code: 'ROLE_UPDATE',
    description: 'Allows modifying role properties and permissions.',
    module: Module.IDENTITY,
    resource: Resource.ROLE,
    action: Action.UPDATE,
    displayOrder: 7,
  },
  {
    name: 'Delete Role',
    code: 'ROLE_DELETE',
    description: 'Allows deleting non-system custom roles.',
    module: Module.IDENTITY,
    resource: Resource.ROLE,
    action: Action.DELETE,
    displayOrder: 8,
  },

  // PERMISSION Permissions
  {
    name: 'Create Permission',
    code: 'PERMISSION_CREATE',
    description: 'Allows creating new granular permissions.',
    module: Module.IDENTITY,
    resource: Resource.PERMISSION,
    action: Action.CREATE,
    displayOrder: 9,
  },
  {
    name: 'Read Permission',
    code: 'PERMISSION_READ',
    description: 'Allows listing and viewing permissions.',
    module: Module.IDENTITY,
    resource: Resource.PERMISSION,
    action: Action.READ,
    displayOrder: 10,
  },
  {
    name: 'Update Permission',
    code: 'PERMISSION_UPDATE',
    description: 'Allows updating permission details and configuration.',
    module: Module.IDENTITY,
    resource: Resource.PERMISSION,
    action: Action.UPDATE,
    displayOrder: 11,
  },
  {
    name: 'Delete Permission',
    code: 'PERMISSION_DELETE',
    description: 'Allows removing access permissions from the system.',
    module: Module.IDENTITY,
    resource: Resource.PERMISSION,
    action: Action.DELETE,
    displayOrder: 12,
  },

  // CLIENT Permissions
  {
    name: 'Create Client',
    code: 'CLIENT_CREATE',
    description: 'Allows creating client organization accounts.',
    module: Module.CRM,
    resource: Resource.CLIENT,
    action: Action.CREATE,
    displayOrder: 13,
  },
  {
    name: 'Read Client',
    code: 'CLIENT_READ',
    description: 'Allows viewing client organization accounts.',
    module: Module.CRM,
    resource: Resource.CLIENT,
    action: Action.READ,
    displayOrder: 14,
  },
  {
    name: 'Update Client',
    code: 'CLIENT_UPDATE',
    description: 'Allows editing client organization accounts.',
    module: Module.CRM,
    resource: Resource.CLIENT,
    action: Action.UPDATE,
    displayOrder: 15,
  },
  {
    name: 'Delete Client',
    code: 'CLIENT_DELETE',
    description: 'Allows deactivating or deleting client organizations.',
    module: Module.CRM,
    resource: Resource.CLIENT,
    action: Action.DELETE,
    displayOrder: 16,
  },

  // LEAD Permissions
  {
    name: 'Create Lead',
    code: 'LEAD_CREATE',
    description: 'Allows creating CRM leads.',
    module: Module.CRM,
    resource: Resource.EMPLOYEE,
    action: Action.CREATE,
    displayOrder: 17,
  },
  {
    name: 'Read Lead',
    code: 'LEAD_READ',
    description: 'Allows viewing CRM leads.',
    module: Module.CRM,
    resource: Resource.EMPLOYEE,
    action: Action.READ,
    displayOrder: 18,
  },
  {
    name: 'Update Lead',
    code: 'LEAD_UPDATE',
    description: 'Allows updating CRM leads.',
    module: Module.CRM,
    resource: Resource.EMPLOYEE,
    action: Action.UPDATE,
    displayOrder: 19,
  },
  {
    name: 'Delete Lead',
    code: 'LEAD_DELETE',
    description: 'Allows removing CRM leads.',
    module: Module.CRM,
    resource: Resource.EMPLOYEE,
    action: Action.DELETE,
    displayOrder: 20,
  },

  // PROJECT Permissions
  {
    name: 'Create Project',
    code: 'PROJECT_CREATE',
    description: 'Allows creating projects.',
    module: Module.PROJECT,
    resource: Resource.PROJECT,
    action: Action.CREATE,
    displayOrder: 21,
  },
  {
    name: 'Read Project',
    code: 'PROJECT_READ',
    description: 'Allows viewing project details.',
    module: Module.PROJECT,
    resource: Resource.PROJECT,
    action: Action.READ,
    displayOrder: 22,
  },
  {
    name: 'Update Project',
    code: 'PROJECT_UPDATE',
    description: 'Allows updating project configuration.',
    module: Module.PROJECT,
    resource: Resource.PROJECT,
    action: Action.UPDATE,
    displayOrder: 23,
  },
  {
    name: 'Delete Project',
    code: 'PROJECT_DELETE',
    description: 'Allows deleting projects.',
    module: Module.PROJECT,
    resource: Resource.PROJECT,
    action: Action.DELETE,
    displayOrder: 24,
  },

  // TASK Permissions
  {
    name: 'Create Task',
    code: 'TASK_CREATE',
    description: 'Allows creating tasks.',
    module: Module.PROJECT,
    resource: Resource.TASK,
    action: Action.CREATE,
    displayOrder: 25,
  },
  {
    name: 'Read Task',
    code: 'TASK_READ',
    description: 'Allows viewing tasks.',
    module: Module.PROJECT,
    resource: Resource.TASK,
    action: Action.READ,
    displayOrder: 26,
  },
  {
    name: 'Update Task',
    code: 'TASK_UPDATE',
    description: 'Allows updating tasks.',
    module: Module.PROJECT,
    resource: Resource.TASK,
    action: Action.UPDATE,
    displayOrder: 27,
  },
  {
    name: 'Delete Task',
    code: 'TASK_DELETE',
    description: 'Allows deleting tasks.',
    module: Module.PROJECT,
    resource: Resource.TASK,
    action: Action.DELETE,
    displayOrder: 28,
  },

  // DOCUMENT Permissions
  {
    name: 'Create Document',
    code: 'DOCUMENT_CREATE',
    description: 'Allows uploading documents.',
    module: Module.PROJECT,
    resource: Resource.REPORT,
    action: Action.CREATE,
    displayOrder: 29,
  },
  {
    name: 'Read Document',
    code: 'DOCUMENT_READ',
    description: 'Allows viewing document metadata.',
    module: Module.PROJECT,
    resource: Resource.REPORT,
    action: Action.READ,
    displayOrder: 30,
  },
  {
    name: 'Update Document',
    code: 'DOCUMENT_UPDATE',
    description: 'Allows updating document details.',
    module: Module.PROJECT,
    resource: Resource.REPORT,
    action: Action.UPDATE,
    displayOrder: 31,
  },
  {
    name: 'Delete Document',
    code: 'DOCUMENT_DELETE',
    description: 'Allows deleting documents.',
    module: Module.PROJECT,
    resource: Resource.REPORT,
    action: Action.DELETE,
    displayOrder: 32,
  },
  {
    name: 'Download Document',
    code: 'DOCUMENT_DOWNLOAD',
    description: 'Allows downloading document binary files.',
    module: Module.PROJECT,
    resource: Resource.REPORT,
    action: Action.DOWNLOAD,
    displayOrder: 33,
  },

  // INVOICE Permissions
  {
    name: 'Create Invoice',
    code: 'INVOICE_CREATE',
    description: 'Allows creating invoices.',
    module: Module.FINANCE,
    resource: Resource.INVOICE,
    action: Action.CREATE,
    displayOrder: 34,
  },
  {
    name: 'Read Invoice',
    code: 'INVOICE_READ',
    description: 'Allows viewing invoices.',
    module: Module.FINANCE,
    resource: Resource.INVOICE,
    action: Action.READ,
    displayOrder: 35,
  },
  {
    name: 'Update Invoice',
    code: 'INVOICE_UPDATE',
    description: 'Allows updating invoices.',
    module: Module.FINANCE,
    resource: Resource.INVOICE,
    action: Action.UPDATE,
    displayOrder: 36,
  },
  {
    name: 'Delete Invoice',
    code: 'INVOICE_DELETE',
    description: 'Allows deleting invoices.',
    module: Module.FINANCE,
    resource: Resource.INVOICE,
    action: Action.DELETE,
    displayOrder: 37,
  },
  {
    name: 'Download Invoice',
    code: 'INVOICE_DOWNLOAD',
    description: 'Allows downloading generated invoice PDFs.',
    module: Module.FINANCE,
    resource: Resource.INVOICE,
    action: Action.DOWNLOAD,
    displayOrder: 38,
  },

  // TICKET Permissions
  {
    name: 'Create Ticket',
    code: 'TICKET_CREATE',
    description: 'Allows creating support tickets.',
    module: Module.SUPPORT,
    resource: Resource.TASK,
    action: Action.CREATE,
    displayOrder: 39,
  },
  {
    name: 'Read Ticket',
    code: 'TICKET_READ',
    description: 'Allows viewing support tickets.',
    module: Module.SUPPORT,
    resource: Resource.TASK,
    action: Action.READ,
    displayOrder: 40,
  },
  {
    name: 'Update Ticket',
    code: 'TICKET_UPDATE',
    description: 'Allows updating support tickets.',
    module: Module.SUPPORT,
    resource: Resource.TASK,
    action: Action.UPDATE,
    displayOrder: 41,
  },
  {
    name: 'Delete Ticket',
    code: 'TICKET_DELETE',
    description: 'Allows deleting support tickets.',
    module: Module.SUPPORT,
    resource: Resource.TASK,
    action: Action.DELETE,
    displayOrder: 42,
  },

  // CAREER / JOB Permissions
  {
    name: 'Create Job',
    code: 'JOB_CREATE',
    description: 'Allows posting career openings.',
    module: Module.CAREER,
    resource: Resource.JOB,
    action: Action.CREATE,
    displayOrder: 43,
  },
  {
    name: 'Read Job',
    code: 'JOB_READ',
    description: 'Allows viewing career openings.',
    module: Module.CAREER,
    resource: Resource.JOB,
    action: Action.READ,
    displayOrder: 44,
  },
  {
    name: 'Update Job',
    code: 'JOB_UPDATE',
    description: 'Allows updating career openings.',
    module: Module.CAREER,
    resource: Resource.JOB,
    action: Action.UPDATE,
    displayOrder: 45,
  },
  {
    name: 'Delete Job',
    code: 'JOB_DELETE',
    description: 'Allows removing career openings.',
    module: Module.CAREER,
    resource: Resource.JOB,
    action: Action.DELETE,
    displayOrder: 46,
  },

  // SYSTEM & AUDIT LOG Permissions
  {
    name: 'Read System Metrics',
    code: 'SYSTEM_READ',
    description: 'Allows viewing system health metrics.',
    module: Module.SYSTEM,
    resource: Resource.DASHBOARD,
    action: Action.READ,
    displayOrder: 47,
  },
  {
    name: 'Read Audit Logs',
    code: 'AUDIT_LOG_READ',
    description: 'Allows viewing system audit logs.',
    module: Module.SYSTEM,
    resource: Resource.DASHBOARD,
    action: Action.EXPORT,
    displayOrder: 48,
  },
];
